# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class ProductItem(scrapy.Item):
    # define the fields for your item here like:
    store_area_id = scrapy.Field()
    store_area_name = scrapy.Field()
    store_area_slug = scrapy.Field()
    store_area_from_map = scrapy.Field()
    store_area_ltd = scrapy.Field()
    store_area_lngt = scrapy.Field()
    store_area_display_name = scrapy.Field()
    store_area_ipse = scrapy.Field()
    store_area_name = scrapy.Field()
    store_area_name = scrapy.Field()
    store_branch_id = scrapy.Field()
    store_branch_name = scrapy.Field()
    store_restaurant_id = scrapy.Field()
    store_logo = scrapy.Field()
    store_description = scrapy.Field()
    store_latitude = scrapy.Field()
    store_longitude = scrapy.Field()
    store_total_reviews = scrapy.Field()
    store_rate = scrapy.Field()
    store_shop_type = scrapy.Field()
    store_is_dark_store = scrapy.Field()
    store_is_migrated = scrapy.Field()
    store_dh_vendor_id = scrapy.Field()
    store_delivery_time_mins = scrapy.Field()
    store_delivery_fee = scrapy.Field()
    store_minimum_order_value = scrapy.Field()
    store_talabat_branch_id = scrapy.Field()
    category = scrapy.Field()
    subcategory = scrapy.Field()
    id = scrapy.Field()
    dh_vendor_id = scrapy.Field()
    title = scrapy.Field()
    slug = scrapy.Field()
    description = scrapy.Field()
    original_price = scrapy.Field()
    price = scrapy.Field()
    discount = scrapy.Field()
    discount_percentage = scrapy.Field()
    image = scrapy.Field()
    image_1 = scrapy.Field()
    image_2 = scrapy.Field()
    image_3 = scrapy.Field()
    image_4 = scrapy.Field()
    image_5 = scrapy.Field()
    image_6 = scrapy.Field()
    image_7 = scrapy.Field()
    image_8 = scrapy.Field()
    image_9 = scrapy.Field()
    image_10 = scrapy.Field()
    image_11 = scrapy.Field()
    image_12 = scrapy.Field()
    image_13 = scrapy.Field()
    image_14 = scrapy.Field()
    image_15 = scrapy.Field()
    image_16 = scrapy.Field()
    stock_amount = scrapy.Field()
    sku = scrapy.Field()
    